---
- name: Add RKE2 binary path to system PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="/var/lib/rancher/rke2/bin:$PATH"'
    state: present

- name: Create kubectl symlink
  file:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    state: link

- name: Create .kube directory for root
  file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Copy kubeconfig for root
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /root/.kube/config
    remote_src: yes
    mode: '0600'

- name: Wait for all nodes to be ready
  shell: kubectl get nodes --no-headers | grep -v Ready | wc -l
  register: not_ready_nodes
  until: not_ready_nodes.stdout == "0"
  retries: 30
  delay: 10

- name: Display cluster information
  shell: kubectl get nodes -o wide
  register: cluster_nodes

- name: Show cluster nodes
  debug:
    var: cluster_nodes.stdout_lines

- name: Display cluster pods
  shell: kubectl get pods -A
  register: cluster_pods

- name: Show cluster pods
  debug:
    var: cluster_pods.stdout_lines

- name: Get cluster info
  shell: kubectl cluster-info
  register: cluster_info

- name: Show cluster info
  debug:
    var: cluster_info.stdout_lines