---
- name: Validate Oracle Linux environment for RKE2
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check Oracle Linux version
      assert:
        that:
          - ansible_distribution == "OracleLinux"
          - ansible_distribution_major_version == "7"
        fail_msg: "This playbook is designed for Oracle Linux 7.x"
        success_msg: "Oracle Linux {{ ansible_distribution_version }} detected"

    - name: Check kernel version compatibility
      assert:
        that:
          - ansible_kernel is version('3.10.0', '>=')
        fail_msg: "Kernel version {{ ansible_kernel }} is too old. Minimum required: 3.10.0"
        success_msg: "Kernel version {{ ansible_kernel }} is compatible"

    - name: Check available memory
      assert:
        that:
          - ansible_memtotal_mb >= 2048
        fail_msg: "Insufficient memory: {{ ansible_memtotal_mb }}MB. Minimum 2GB required"
        success_msg: "Memory check passed: {{ ansible_memtotal_mb }}MB available"

    - name: Check disk space
      shell: df -h / | awk 'NR==2 {print $4}' | sed 's/G//'
      register: available_space
      changed_when: false

    - name: Validate disk space
      assert:
        that:
          - available_space.stdout | int >= 20
        fail_msg: "Insufficient disk space: {{ available_space.stdout }}GB. Minimum 20GB free required"
        success_msg: "Disk space check passed: {{ available_space.stdout }}GB available"

    - name: Check network connectivity
      uri:
        url: https://get.rke2.io
        method: HEAD
        timeout: 10
      register: network_check
      failed_when: false

    - name: Validate internet connectivity
      assert:
        that:
          - network_check.status == 200
        fail_msg: "Cannot reach RKE2 download site. Check internet connectivity"
        success_msg: "Internet connectivity verified"